# syntax=docker/dockerfile:1
FROM debian:testing-slim

# Set environment variables to prevent interactive prompts during builds
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages
RUN apt update && \
    apt install --no-install-recommends -y \
    systemd systemd-sysv dbus slurmd && \
    apt clean && rm -rf /var/lib/apt/lists/*

# Ensure systemd works inside the container
VOLUME [ "/sys/fs/cgroup" ]

# Copy entrypoint script
#COPY entrypoint-slurmd.sh /usr/local/bin/entrypoint.sh
#RUN chmod +x /usr/local/bin/entrypoint.sh

# Copy systemd service file for slurmd
#COPY slurmd.service /etc/systemd/system/slurmd.service
#RUN systemctl enable slurmd

# Expose Slurmd port
EXPOSE 6818/tcp

# Set default command to run systemd as PID 1
CMD ["/lib/systemd/systemd"]
