apiVersion: v1
kind: ConfigMap
metadata:
  name: slurm-config
  namespace: jsfillman
data:
  slurm.conf: |
    ClusterName=slurm-cluster
    SlurmctldHost=slurmctld-0
    SlurmUser=slurm
    SlurmdUser=slurm
    SlurmdSpoolDir=/tmp/slurmd
    StateSaveLocation=/tmp/slurmctld
    AuthType=none
    CryptoType=none
    MailProg=/bin/true
    SlurmctldLogFile=/tmp/slurm/slurmctld.log
    SlurmctldDebug=info
    SlurmdLogFile=/tmp/slurm/slurmd.log
    SlurmdDebug=info
    SlurmctldPort=6817
    SlurmdPort=6818
    NodeName=slurmd-[0-3] CPUs=4 State=UNKNOWN
    PartitionName=debug Nodes=ALL Default=YES MaxTime=INFINITE State=UP
