apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: slurmd
  namespace: jsfillman
spec:
  serviceName: slurmd
  replicas: 2
  selector:
    matchLabels:
      app: slurmd
  template:
    metadata:
      labels:
        app: slurmd
    spec:
      securityContext:
        runAsUser: 64030
        runAsGroup: 64030
        fsGroup: 64030
      containers:
        - name: slurmd
          image: jsfillman/slurmd:slinky
          command: ["sleep", "infinity"]
          securityContext:
            runAsUser: 64030
            runAsGroup: 64030
          ports:
            - containerPort: 7003
          volumeMounts:
            - name: slurm-config
              mountPath: /etc/slurm/slurm.conf
              subPath: slurm.conf
            - name: slurm-config
              mountPath: /etc/slurm/cgroup.conf
              subPath: cgroup.conf
            - name: slurmd-spool
              mountPath: /var/spool/slurmd
            - name: slurmd-logs
              mountPath: /var/log/slurm
      volumes:
        - name: slurm-config
          configMap:
            name: slurm-config
        - name: slurmd-spool
          emptyDir: {}
        - name: slurmd-logs
          emptyDir: {}
